### ISSUE TITLE
Don't Archive Tasks Automatically – Option

### ISSUE THREAD

**Issue by kennonb** [jgclark/NotePlan-tools#14]
I like to use the `## Done` section sporadically. It'd be nice if there was an option flag to disable this. I have the piece of code that needs to be changed, but I'm not 100% familiar with Ruby to add an option.

- [ ] Add option conditional around lines 283-420

**Comment by kennonb** [comment]
#16: Not sure if these naming schemes will work, but here's a stab at this change.

**Comment by jgclark** [comment]
I've incorporated your changes, with a few tweaks for code consistency, and is now available in v1.4.1.
Many thanks.

**Comment by kennonb** [comment]
Thanks for this tool! This has been really nice to have with NP. 👍🏻
