### ISSUE TITLE
Don't Remove Scheduled Text From Completed Tasks – Option

### ISSUE THREAD

**Issue by kennonb** [jgclark/NotePlan-tools#15]
I found that in order to see a running list of completed tasks in the Filters, I have to keep the scheduled text on the completed tasks. It'd be nice if there was an option flag to disable this. I have the piece of code that needs to be changed, but I'm not 100% familiar with Ruby to add an option.

- [ ] Add option conditional around lines 136-140

**Comment by kennonb** [comment]
#16: Ok I think I figured it out. 😊

**Comment by jgclark** [comment]
I think you have! Now available in v1.4.1.
