### ISSUE TITLE
Rewritten /Calendar items being placed in /Notes

### ISSUE THREAD

**Issue by BMStroh** [jgclark/NotePlan-tools#25]
Found the commonality for the files that are getting moved - 

Regex on line 106 doesn't take into account the new .md extension for files.  Later on, in rewrite_files (line 666), any rewritten daily note gets moved to Notes if you're using the .md extension.

    # Now make a title for this file:
    **if @filename =~ /\d{8}\.txt/**
      # for Calendar file, use the date from filename
      @title = @filename[0..7]
      @is_calendar = true
    else
      # otherwise use first line (but take off heading characters at the start and starting and ending whitespace)
      tempTitle = @lines[0].gsub(/^#+\s*/, '')
      @title = tempTitle.gsub(/\s+$/, '')
      @is_calendar = false
    end
  end

**Comment by jgclark** [comment]
Thanks for reporting this. I'd not realised this code in initialisation of an NPNote object would affect writing out files.
I've changed the regex to allow for `.md` as well as `.txt` files.

**Comment by BMStroh** [comment]
Got back to this a bit earlier today and this seems to work without moving the file on my side, and the app immediately recognizes the change and refreshes the daily note.  CloudKit here, and I rarely update notes via iOS.  I set my default extension to .md and worked through the rename/sync growing pains when the feature was first released if that’s useful from a troubleshooting standpoint.


    if @filename =~ /\d{8}\.txt/ || @filename =~ /\d{8}\.md/

**Comment by jgclark** [comment]
The developer said in Discord earlier today:
> NotePlan detects strictly the extension you defined for calendar notes, but non-calendar notes can be anything. Just when you create a new one it uses the defined extension.

So I've added .md as an understood option for calendar files. @BMStroh, I hope this fixes the issue, with a6461cf145565986654048a5acfc3437940523cc.
