### ISSUE TITLE
If the first line of a file is an "empty header" it won't be deleted on cleanup

### ISSUE THREAD

**Issue by BMStroh** [jgclark/NotePlan-tools#33]
Probably an unusual case, but the fix is on line 692 - add || n.zero? so the loop makes it back to the first entry in the array. 

    later_header_level = this_header_level = 0
    at_eof = 1
    while n.positive? || n.zero?
      line = @lines[n]
      # find header lines

**Comment by jgclark** [comment]
Thanks. Have pushed an update that includes this.
